name: Enforce advanced security scanning

on:
  workflow_dispatch:
  schedule:
    - cron: '55 18 * * *'

jobs:
  build:
    name: Enforce advanced security scanning
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Run enforcer tool
      uses: docker://ghcr.io/zkoppert/advanced-security-enforcer:test
      env:
        GH_ACTOR: ${{ secrets.GH_ACTOR }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        ORGANIZATION: super-linter
        PR_BODY: Please merge this PR once all the checks pass. It will enable GitHub Advanced Security code scanning in your repository.
